Algoritmo "Amoricha"

// Descrição   : Declaracao para amoricha
// Autor(a)    : Fernando A. de Faria
// Data atual  : 09/04/2020
Var
// Seção de Declarações das variáveis 
   nome1, nome2: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Ola, bem-vindo(a), qual o seu nome?")
   leia(nome1)
   escreval(nome1, ", qual o nome do seu marido?")
   leia(nome2)
   escreval(nome1, ", saiba que ", nome2, " TE AMA muitaozaoaozao!")

Fimalgoritmo