Algoritmo "Variaveis"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Cleiton Melo
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Fernando Augusto de Faria
// Data atual  : 09/04/2020
Var
// Seção de Declarações das variáveis
   nota: inteiro, nota2: real, nome: caractere, passou: logico;

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo